### ISSUE TITLE
 React does not recognize props

### ISSUE THREAD

**Issue by HeleneKassandra** [donovanclarke/react-lottie#2]
Hi, this is my first time using Lottie in general, but I seem to be getting these error when the animation run? But as far as I understood these props are optional? 
![image](https://user-images.githubusercontent.com/39946146/82156745-5b668200-987d-11ea-9527-b7c3b378287c.png)

My component: 
```
import React from "react";
import Lottie from "react-lottie-wrapper";
import * as LogoAnimation from "../../assets/LogoAnimation.json";
const LogoLoader = () => {
    const defaultOptions = {
        loop: true,
        autoplay: true,
        animationData: LogoAnimation.default,
        rendererSettings: {
            preserveAspectRatio: "xMidYMid slice"
        }
    };
    return (
        <div className="logoloader_container">
            <Lottie
                options={defaultOptions}
                height={200}
                width={200}
            />
            <span className="logoloader-text">LOADING..</span>
        </div>
    )
}

export default LogoLoader;
```

**Comment by donovanclarke** [comment]
@HeleneJuterud, my apologies. The props were being spread and this caused these warnings to be displayed in the console. If you bump your version to 1.1.8, this should fix the issue.

Thanks, again for bringing this issue forward. Please let me know if you are getting any other warnings. I double checked in the console and it seems they have disappeared. 

Thanks!
